apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-irs
  labels:
    app: poc-irs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-irs
  template:
    metadata:
      labels:
        app: poc-irs
    spec:
      containers:
        - name: poc-irs-container
          image: gokulmeyghanam/irs:latest
          ports:
            - containerPort: 9292
---
apiVersion: v1
kind: Service
metadata:
  name: poc-irs
spec:
  selector:
    app: poc-irs
  ports:
    - protocol: TCP
      port: 9292
      targetPort: 9292
  type: ClusterIP